
forecastSimple:
    path: /forecast2/index
    defaults: {_controller: AppBundle:Forecast:index}
forecastParam:
    path: /forecast2/{weather}
    defaults: {_controller: AppBundle:Forecast:indexParam, weather: nublado}
forecast2Param:
    path: /forecast2/{weather}/{temp}
    defaults: {_controller: AppBundle:Forecast:index2Params, weather: lluvioso, temp: 27}
forecast_request_param:
    path: /forecast2/indexRequest/{weather}/{temp}
    defaults: {_controller: AppBundle:Forecast:indexRequest, weather: lluvioso, temp: 27}
redirect_index:
    path: /redirect/index
    defaults: {_controller: AppBundle:Redirect:index}
redirect_interna_index:
    path: /redirectinterna/index
    defaults: {_controller: AppBundle:Redirect:internalRedirect}
get_temp:
    path: /temperature/{id}
    defaults: {_controller: AppBundle:Temperature:get}
    requirements: 
        id: \d+
check_temp: 
    path: /temperature/check
    defaults: {_controller: AppBundle:Temperature:check}
get_all:
    path: /temperature/all
    defaults: {_controller: AppBundle:Temperature:getAll}
location_index: 
    path: /location/index
    defaults: {_controller: AppBundle:Location:index}
location_json:
    path: /location/json
    defaults: {_controller: AppBundle:Location:indexJson}
standalone: 
    path: /standalone
    defaults:
     _controller: FrameworkBundle:Template:template
     template: standalone/index.html.twig
     maxAge: 86400
     sharedAge: 86400