#forecast_simple:
   # path: /forecast2/index
   # defaults: {_controller: AppBundle:Forecast:index}

#forecast_tiempo:
  #  path: /forecast2/hola
   # defaults: {_controller: AppBundle:Tiempo:hola}

#forecast_param:
 #   path: /forecast2/{hola}
 #   defaults: {_controller: AppBundle:Tiempo:holaParam, hola: saludo}

#forecast_param:
  # path: /forecast2/{weather}
   # defaults: {_controller: AppBundle:Forecast:indexParam, weather: nublado}

#forecast_2_params:
  #  path: /forecast2/{weather}/{temperature}
  #  defaults: {_controller: AppBundle:Forecast:index2Params, weather: lluvioso, temperature: 27}

#forecast_request_params:
    #path: /forecast2/indexRequest/{weather}/{temperature}
    #defaults: {_controller: AppBundle:Forecast:indexRequest, weather: nublado, temperature: 14}

redirect_index:
    path: /redirect/index
    defaults: {_controller: AppBundle:Redirect:index}

redirect_interna_index:
    path: /redirectinterna/index
    defaults: {_controller: AppBundle:Redirect:internaRedirect}

redirect_interna_permanent_index:
    path: /redirectinternapermanent/index
    defaults: {_controller: AppBundle:Redirect:internaRedirectPermanent}

redirect_externa_index:
    path: /redirectexterna/index
    defaults: {_controller: AppBundle:Redirect:externaRedirect}

#get_temp:
    #path: /temperature/{id}
    #defaults: {_controller: AppBundle:Temperature:get}
    #requirements: 
        #id: \id+

#check_temp:
  #  path: /temperature/check
  #  defaults: {_controller: AppBundle:Temperature:check}

#location_index:
  #  path : /location/index
    #defaults: {_controller: AppBundle:Location:index}

#respuesta_json:
  #  path: /location/json
  #  defaults: {_controller: AppBundle:Location:indexJson}

#standalone:
   # path: /standalone
   # defaults:
      #  _controller: FrameworkBundle:Template:template
     #   template: standalone/index.html.twig
      #  maxAge: 86400
      #  sharedAge: 86400

#forward_index:
 #   path: /forward
  #  defaults: {_controller: AppBundle:Forward:index}

#pasar algo por parametros y te lo enseña
#forecast_algo:
 #   path: /forecast2/{algo}
  #  defaults: {_controller: AppBundle:Greet:algoParam, algo: algo}

#calculadora
forecast_calculator:
    path: /forecast2/sum/{num1}/{num2}
    defaults: {_controller: AppBundle:Calculator:sumParams, num1: 10, num2: 2}

    #usuario distinto a admin devuelve exception si no mensaje 
get_user:
    path: /calculator/{username}
    defaults: {_controller: AppBundle:Calculator:get}

forward_usuario:
    path: /session
    defaults: {_controller: AppBundle:Session:user}

login_session:
    path: /session/{user}/{passwd}
    defaults: {_controller: AppBundle:Session:loginParams}


redirectSession:
   path: /redirectSession
   defaults:
      _controller: FrameworkBundle:Template:template
      template: session/session.html.twig