#Ejercicio 1

index: 
    path: /{mensaje}
    defaults: {_controller: AppBundle:Ejercicio1:index}

vista:
    path: /vista/{mensaje}
    defaults: {_controller: AppBundle:Ejercicio1:get}

suma:
    path: /suma/{num1}/{num2}
    defaults: {_controller: AppBundle:Ejercicio1:suma, num1: 5, num2: 5}
resta:
    path: /resta/{num1}/{num2}
    defaults: {_controller: AppBundle:Ejercicio1:resta, num1: 5, num2: 5} 
multiplicacion:
    path: /multipli/{num1}/{num2}
    defaults: {_controller: AppBundle:Ejercicio1:multipli, num1: 5, num2: 5}
division:
    path: /divide/{num1}/{num2}
    defaults: {_controller: AppBundle:Ejercicio1:divide, num1: 5, num2: 5} 



#Ejercicio 2 
redirect_index:
    path: /redirect/index
    defaults: {_controller: AppBundle:Ejercicio2:index}

redirect_interna_index:
    path: /redirectinterna/index
    defaults: {_controller: AppBundle:Ejercicio2:internalRedirect}

redirect_interna_permanent_index:
    path: /redirectinternapermanente/index
    defaults: {_controller: AppBundle:Ejercicio2:internalRedirectPermanent}

redirect_externa_index:
    path: /redirectexterna/index
    defaults: {_controller: AppBundle:Ejercicio2:externaRedirect}